AWSTemplateFormatVersion: "2010-09-09"

Description: AWS DevOps Course Manifold AI Learning

Resources:
  Table1:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Album
          AttributeType: S
        - AttributeName: Artist
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: Album
          KeyType: HASH
        - AttributeName: Artist
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  Queue1:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 345600
