AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template creates an EC2 Instance on AZ us-east-1a, with the mentioned ImageId'

Mappings: 
  RegionMap: 
    us-east-1: 
      HVM64: "ami-0ff8a91507f77f867"
      HVMG2: "ami-0a584ac55a7631c0c"
    us-west-1: 
      HVM64: "ami-0bdb828fd58c52235"
      HVMG2: "ami-066ee5fd4a9ef77f1"
    eu-west-1: 
      HVM64: "ami-047bb4163c506cd98"
      HVMG2: "ami-31c2f645"
    ap-southeast-1: 
      HVM64: "ami-08569b978cc4dfa10"
      HVMG2: "ami-0be9df32ae9f92309"
    ap-northeast-1: 
      HVM64: "ami-06cd52961ce9f0d85"
      HVMG2: "ami-053cdd503598e4a9d"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: t2.micro
      KeyName: aws-devops
      Tags:
        - Key: "Name"
          Value: "intrinsic-functions-Manifold-AI-Learning"
        - Key: "Course"
          Value: "DevOps"
      SecurityGroups:
      - Ref: WebServerSecurityGroup
      UserData:
        Fn::Base64: |
           #!bin/bash
           sudo yum update -y
           sudo yum install -y ruby wget
           wget https://aws-codedeploy-eu-west-1.s3.eu-west-1.amazonaws.com/latest/install
           chmod +x ./install
           sudo ./install auto
           sudo service codedeploy-agent status 
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 80 + SSH access"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '80'
        IpProtocol: tcp
        ToPort: '80'
      - CidrIp: 0.0.0.0/0
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'